IF (EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_SCHEMA = 'dbo' 
                 AND  TABLE_NAME = 'POSUser'))
BEGIN
CREATE TABLE POSUser (
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Name VARCHAR(255) NOT NULL,
	AuthenticationToken VARCHAR(255) NOT NULL,
	MerchantName VARCHAR(255) NOT NULL,
	MerchantKey VARCHAR(255) NOT NULL,
	ConfigurationID VARCHAR(255) NULL DEFAULT('')
)
END
